import React, { useState } from "react";
import { ArrowForwardIcon } from "@chakra-ui/icons";
import {
	AlertDialogBody,
	AlertDialogCloseButton,
	AlertDialogContent,
	AlertDialogFooter,
	AlertDialogHeader,
	Button,
	Icon,
} from "@chakra-ui/react";
import { getAuth, GoogleAuthProvider, signInWithPopup } from "firebase/auth";
const provider = new GoogleAuthProvider();
import toast from "react-hot-toast";
import { useDispatch } from "react-redux";
import types from "../../../redux/types";

export default function LoginDialog({ onClose, cancelRef }) {
	const [isLoading, setIsLoading] = useState(false);
	const dispatch = useDispatch();

	const userLogin = (user) => {
		try {
            dispatch({ type: types.login, payload: user });
            dispatch({ type: types.closeDialog });
            toast.success("Logged In!")
		} catch (error) {
			toast.error(error.message || error);
		}
	};

	const handleLogin = () => {
		setIsLoading(true);
		const auth = getAuth();
		signInWithPopup(auth, provider)
			.then((result) => {
				// const credential = GoogleAuthProvider.credentialFromResult(result);
				// const token = credential.accessToken;
				const user = {
					name: result?.user?.displayName,
					email: result?.user?.email,
					photo: result?.user?.photoURL,
				};
				userLogin(user);
			})
			.catch((error) => {
				toast.error(error.message || error);
			})
			.finally(() => setIsLoading(false));
	};

	return (
		<AlertDialogContent>
			<AlertDialogHeader>Login to your account</AlertDialogHeader>
			<AlertDialogCloseButton />
			<AlertDialogBody>
				By login you can see all the images generated by you at one place, and
				also manage their visibility
			</AlertDialogBody>
			<AlertDialogFooter>
				<Button
					width="100%"
					rightIcon={<ArrowForwardIcon />}
					colorScheme="blue"
					variant="solid"
					isLoading={isLoading}
					onClick={handleLogin}
				>
					Continue with Google
				</Button>
			</AlertDialogFooter>
		</AlertDialogContent>
	);
}
